### ISSUE TITLE
EdmName option bug

### ISSUE THREAD

**Issue by spot62** [voronov-maxim/OdataToEntity#51] opened 2020-12-31 14:10 UTC
Hi!
I'm tested version 2.6 AspServer example with config:

```json
{
  "Tables": [
    {
      "DbName": "dbo.account",
      "EdmName": "Accounts"
    }
  ]
}
```

and the request GET http://localhost:5000/api/Accounts do responsing :

```json
{"@odata.context":"http://localhost:5000/api/$metadata#Accounts","value":[
```
the log error:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM5DIGDM65NR", Request id "0HM5DIGDM65NR:00000002": An unhandled exception was thrown by the application.
      Microsoft.Data.SqlClient.SqlException (0x80131904): Недопустимое имя объекта "dbo.Accounts".
         at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__169_0(Task`1 result)
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

if do change config to:
```json
{
  "Tables": [
    {
      "DbName": "dbo.account",
      "EdmName": "account"
    }
  ]
}
```

the request GET http://localhost:5000/api/account return right response.

But need Accounts instead;) How to fix it?

Thank you!

**Comment by voronov-maxim** [comment] 2020-12-31 15:46
Hi @spot62!

I cannot reproduce this bug.
Try get last version form github.
If bug not fixed on github version, me need a database schema script like [this](https://github.com/voronov-maxim/OdataToEntity/blob/master/test/sql_scripts/sqlserver.sql) and InformationSchemaMapping.json file.

**Comment by spot62** [comment] 2020-12-31 17:50
Sorry, before I caught this bug I was getting an error:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM5E97PH1S2N", Request id "0HM5E97PH1S2N:00000002": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
         at Microsoft.OData.MessageStreamWrapper.MessageStreamWrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
         at Microsoft.OData.AsyncBufferedStream.FlushSync()
         at Microsoft.OData.JsonLight.ODataJsonLightOutputContext.Dispose(Boolean disposing)
         at Microsoft.OData.ODataOutputContext.Dispose()
         at Microsoft.OData.ODataMessageWriter.Dispose(Boolean disposing)
         at Microsoft.OData.ODataMessageWriter.Dispose()
         at OdataToEntity.Writers.OeGetWriter.SerializeAsync(OeQueryContext queryContext, IAsyncEnumerator`1 asyncEnumerator, String contentType, Stream stream, OeEntryFactory entryFactory, IServiceProvider serviceProvider, CancellationToken cancellationToken) in D:\lovitel\crm\OdataToEntity-2.6.0\source\OdataToEntity\Writers\OeGetWriter.cs:line 63
         at OdataToEntity.Parsers.OeGetParser.ExecuteAsync(ODataUri odataUri, OeRequestHeaders headers, Stream stream, CancellationToken cancellationToken) in D:\lovitel\crm\OdataToEntity-2.6.0\source\OdataToEntity\Parsers\OeGetParser.cs:line 71
         at OdataToEntity.Parsers.OeGetParser.ExecuteAsync(ODataUri odataUri, OeRequestHeaders headers, Stream stream, CancellationToken cancellationToken) in D:\lovitel\crm\OdataToEntity-2.6.0\source\OdataToEntity\Parsers\OeGetParser.cs:line 77
         at OdataToEntity.OeParser.ExecuteQueryAsync(ODataUri odataUri, OeRequestHeaders headers, Stream responseStream, CancellationToken cancellationToken) in D:\lovitel\crm\OdataToEntity-2.6.0\source\OdataToEntity\OeParser.cs:line 184
         at OdataToEntity.OeParser.ExecuteGetAsync(Uri requestUri, OeRequestHeaders headers, Stream responseStream, CancellationToken cancellationToken) in D:\lovitel\crm\OdataToEntity-2.6.0\source\OdataToEntity\OeParser.cs:line 179
         at OdataToEntity.AspNetCore.OeMiddleware.InvokeApi(HttpContext httpContext) in D:\lovitel\crm\OdataToEntity-2.6.0\source\OdataToEntity.AspNetCore\OeMiddleware.cs:line 100
         at OdataToEntity.AspNetCore.OeMiddleware.Invoke(HttpContext httpContext) in D:\lovitel\crm\OdataToEntity-2.6.0\source\OdataToEntity.AspNetCore\OeMiddleware.cs:line 85
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
and I added following code from SO to ConfigureServices:

```
      // If using Kestrel:
      services.Configure<KestrelServerOptions>(options =>
      {
          options.AllowSynchronousIO = true;
      });
```

maybe this is the problem?

but how me fix "Synchronous operations are disallowed etc" ?

Thank you.

**Comment by voronov-maxim** [comment] 2020-12-31 19:01
Send me a request that throws an InvalidOperationException and a database schema script.

**Comment by spot62** [comment] 2021-01-01 11:48
The failed request is http://localhost:5000/api/Accounts

The latest commit from master branch works correctly. Thank you!

**Closed as completed** 2021-01-01 11:54 UTC
Labels: question
